### ISSUE TITLE
Unused uart_bus in yaml

### ISSUE THREAD

**Issue by jimmypuckett** [a-lost-shadow/gosund-sw2#4]
In the yaml file you have

```yaml
uart:
  id: uart_bus
  baud_rate: 115200
  tx_pin: GPIO1
  rx_pin: GPIO
```

but I don't see it being used.  Am I missing something?
